### ISSUE TITLE
Boolean value was endcode to byte value

### ISSUE THREAD

**Issue by huytower** [MinimineLP/dart-gson#6]
I used your library to save the Object, it's okay.

Then I recognize there is different related to `boolean` value as below Log description :

```
setUser(User u) async {
    SharedPreferences p = await SharedPreferences.getInstance();

    print("setUser() : ${u.toJson()}");
    //  ${u.toJson()} : {isVIP: true, displayName: X}

    p.setString(USER, gsonEncode(u.toJson()));
    //  After gsonEncode : {isVIP: 1b, displayName: X}.  // I read it from Prefs.
  }
```

It looks like your library convert [true|false] value to [1b|0b] value.

Could you could keep its original value?
since It help me get it boolean value from Prefs. correct.

```
Map<String, dynamic> json = gsonDecode(result);

        User d = User.fromJson(json);

        return d;
```

```
class User {

   static const KEY_IS_VIP = 'isVIP';
  static const KEY_DISPLAY_NAME = 'displayName';

  final bool isVIP;

  final String displayName;

  User({this.isVIP, this.displayName});

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      isVIP : json['$KEY_IS_VIP'] as bool,
      displayName : json['$KEY_DISPLAY_NAME'],
    );
  }
}
```

p/s : Version 1.0.4

**Comment by huytower** [comment]
Currently I need the trick as below to solve this issue temporary

```
Future<User> getUser() async {
    SharedPreferences p = await SharedPreferences.getInstance();

    String result = p.getString(USER);
    if (result != null) {
      Map<String, dynamic> json = gsonDecode(result);

      String byte = json['${User.KEY_IS_VIP}'].toString();

      if (byte == '1b')
        json['${User.KEY_IS_VIP}'] = true;
      else
        json['${User.KEY_IS_VIP}'] = false;

      User d = User.fromJson(json);

      return d;
    } else
      return null;
  }
```

**Comment by MinimineLP** [comment]
The converting from Booleans to bytes ist actually intendet, the reason for that ist that the orginal gson does the same. As described in the docs the problem folowing out of that is, that the library can't see a difference between booleans and bytes with the value 1/0. There is a non-documented feature that actually allows you to do the stuff you wanted to do. It does not follow the standart gson rules, but it does exactly what you want. The feature is called jsonBooleans and adds the option to generate a boolean as true / false instead of 1b / 0b. For example you can use it like that
```dart
gson.encode({"testkey": true}, jsonBooleans: true); // will generate {testkey: true} unstead of {testkey: 1b}
```
The parser is able to parse these values and as they are exactly identifiable as booleans, they will be parsed as boolean values directly.

You can use byte.boolValue insted of your manual check, that makes your code much easier, so this

```dart
String byte = json['${User.KEY_IS_VIP}'].toString();

if (byte == '1b')
  json['${User.KEY_IS_VIP}'] = true;
else
  json['${User.KEY_IS_VIP}'] = false;
```
Would be this

```dart
json['${User.KEY_IS_VIP}'] = json['${User.KEY_IS_VIP}'].boolValue
```

But for your project the easiest solution would be as told this.
```dart
gsonEncode(u.toJson(), jsonBooleans: true);
```
