### ISSUE TITLE
Could not get terminal size

### ISSUE THREAD

**Issue by stoneLee81** [MinimineLP/dart-gson#7]
json str is "{url: , size: 0, second: 3, mediaId: null, downloadFlag: null}"
gson.decode(this json str), throw below exception:

unhandled exception:
StdoutException: Could not get terminal size, OS Error: Not a typewriter, errno = 25
#0      Stdout._terminalSize (dart:io-patch/stdio_patch.dart:147:7)
#1      Stdout._terminalColumns (dart:io-patch/stdio_patch.dart:140:35)
#2      Stdout.terminalColumns (dart:io/stdio.dart:232:30)
#3      terminalColumns (package:gson/terminal_vm.dart:4:35)

**Comment by MinimineLP** [comment]
@stoneLee81 
Is the problem solved for you? Sorry, I am very busy at the moment, and had no time to respond at all.
If its not working, can you please tell me, if you are using te sdk or flutter? The error seems to appear caused by the error formatter, that uses the terminal width to generate beautier exceptions. Propably I should overthink this system as it seems to be responsible for many errors.

**Comment by ychawla29** [comment]
I am facing the same issue can you tell me the solution ?

My JSON = {"type":"response","version":"1.0.0","requestId":"0EzDL50Vdm4S0QhBqo1nyNLt","locale":"en","status":[{"statusMessage":"Success","statusCode":"000"}],"cmd":{"cmdName":"getAppGroup","rowSize":"-1"},"resultAttrs":{"result":[{"name":"FDS","isDefault":false,"createdBy":{"id":3},"id":2}]}}
